
# export HOMEBREW_BUNDLE_BREW_SKIP =
# export HOMEBREW_BUNDLE_CASK_SKIP =
# export HOMEBREW_BUNDLE_MAS_SKIP =
# export HOMEBREW_BUNDLE_WHALEBREW_SKIP =
# export HOMEBREW_BUNDLE_TAP_SKIP =

bundle:
	brew bundle --no-lock

install:
	brew bundle install

dump:
	brew bundle dump

force-dump:
	brew bundle dump --force

