# When no configuration file is found, Ruff will look for a user-specific `ruff.toml` file as a last resort.
#
# On macOS and Linux, Ruff expects that file to be located at `~/.config/ruff/ruff.toml`, and respects the `XDG_CONFIG_HOME` specification.
#
# On Windows, Ruff expects that file to be located at `~\AppData\Roaming\ruff\ruff.toml`.
line-length = 88
indent-width = 4
extend-exclude = [".venv*"]
preview = true

[format]
docstring-code-format = true
docstring-code-line-length = 79
# preview = true
skip-magic-trailing-comma = true

[lint]
typing-modules = ["collections.abc"]
# preview = true

extend-ignore = [
    "E501",    # Line too long (95 > 88 characters)
    "S101",    # Use of `assert` detected
    "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
    # "B027",    # Allow non-abstract empty methods in abstract base classes
    # "D100",    # Missing docstring in public module
]

extend-fixable = ["UP"]
unfixable = [
    "F401", # Don't touch unused imports
]
