#:schema https://developers.openai.com/codex/config-schema.json

file_opener = "vscode"
model = "gpt-6-astra"
model_reasoning_effort = "max"
service_tier = "default"

[features]
memories = true

[memories]
generate_memories = true
use_memories = true

[analytics]
enabled = false

[apps.connector_20205bf7d4e99a89d7154bb849718324] # app: Sites
enabled = false

[marketplaces.ponytail]
last_updated = "2026-08-08T09:15:36Z"
last_revision = "2ed6c52c9d7e5e56942508591085fd45dea277d3"
source_type = "git"
source = "https://github.com/DietrichGebert/ponytail.git"

[plugins."ponytail@ponytail"]
enabled = true

[hooks.state]

[hooks.state."ponytail@ponytail:hooks/claude-codex-hooks.json:session_start:0:0"]
trusted_hash = "sha256:5f81d38f47448a1581c08ec877e044d9e04dd6f814dce3f2671f7a8edadd719b"

[hooks.state."ponytail@ponytail:hooks/claude-codex-hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:6a6f42bc3b58d6262db38bfd74d7f340fcca2b09cdb134aad365063f0bfefca4"

[hooks.state."ponytail@ponytail:hooks/claude-codex-hooks.json:subagent_start:0:0"]
trusted_hash = "sha256:1423b56c1322f96c8f74c51c1e7ae9a047b904c1fa43ee9165d462fd7a6e70ef"
