#:schema https://developers.openai.com/codex/config-schema.json

file_opener = "vscode"

[features]
memories = true

[memories]
generate_memories = true
use_memories = true

[analytics]
enabled = false

# App: Sites
[apps.connector_20205bf7d4e99a89d7154bb849718324]
enabled = false
