# https://pnpm.io/settings

minimumReleaseAge: 1440
savePrefix: ''
# The following options can be used to enforce stricter rules
#
# catalogMode: strict
# cleanupUnusedCatalogs: true
# engineStrict: true
# linkWorkspacePackages: true
# packageManagerStrictVersion: true
# preferWorkspacePackages: true
# resolutionMode: time-based # https://stackoverflow.com/a/74935908
# strictDepBuilds: true
# strictPeerDependencies: true
